name: Publish snapshots

on: [push]

permissions: read-all

jobs:
  gradle:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [ '8', '11', '17', '19' ] # Gradle cannot support JDK 20 yet

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
        cache: 'gradle'

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: check --console=plain --warning-mode all

  publish:
    name: Publish Artifact
    needs: gradle
    if: ${{ needs.gradle.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        cache: 'gradle'

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build -x test publish
      env:
        GPR_USERNAME: benfortuna
        GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
